# Generated by Django 5.0.7 on 2024-07-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_document_approved_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='approved',
        ),
    ]
