# Generated by Django 5.0.7 on 2024-07-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_document_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
