# Generated by Django 5.0.7 on 2024-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_document_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
